apiVersion: v1
kind: Secret

metadata:
  name: shortlink-mysql-secret
  namespace: url-shortner

type: Opaque

stringData:
  root-password: rootpass
  username: shortlink_user
  password: shortlink_pass
  database: shortlink_db