apiVersion: v1
kind: Service

metadata:
  name: shortlink-mysql
  namespace: url-shortner

spec:
  selector:
    app: shortlink-mysql

  ports:
    - port: 3306
      targetPort: 3306

  type: ClusterIP