apiVersion: v1
kind: Service

metadata:
  name: shortlink-redis
  namespace: url-shortner

spec:
  selector:
    app: shortlink-redis

  ports:
    - port: 6379
      targetPort: 6379

  type: ClusterIP