apiVersion: v1
kind: Service

metadata:
  name: url-shortner
  namespace: url-shortner

spec:
  selector:
    app: url-shortner

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

  type: NodePort